const SHIFT={M:["06:50","14:40"],J:["08:30","16:20"],J4:["10:10","18:00"],S:["13:30","21:00"],N:["20:50","06:50"]};
const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().trim();
const agentKey=v=>norm(v).replace(/[^A-Z0-9]+/g,"_").replace(/^_+|_+$/g,"");
function cleanShift(v){const s=norm(v).replace(/[❶❷❸❹❺❻❼❽❾➊➋➌➍➎➏➐➑➒]/g,"").replace(/\*/g,"").trim();if(/^M\d+$/.test(s))return"M";if(/^J4\d*$/.test(s)||s==="J4")return"J4";if(/^J\d+$/.test(s)||s==="J")return"J";if(/^S\d+$/.test(s)||s==="S")return"S";if(/^N\d*$/.test(s)||s==="N")return"N";return s.replace(/[^A-Z0-9]/g,"")}
const hours=v=>SHIFT[cleanShift(v)]||null;
const avatar=a=>a?.avatar_id?`https://drive.google.com/thumbnail?id=${encodeURIComponent(a.avatar_id)}&sz=w320`:(a?.avatar_url||"");
function out(x,status=200,cb=""){const h={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};if(cb&&/^[A-Za-z_$][\w$.]*$/.test(cb))return new Response(`${cb}(${JSON.stringify(x)});`,{status,headers:{...h,"Content-Type":"application/javascript; charset=utf-8"}});return Response.json(x,{status,headers:h})}
async function rpc(context,mode,agent=null,type=null){const env=context.env||{};const base=String(env.SUPABASE_URL||"").replace(/\/$/,"");const key=env.SUPABASE_PUBLISHABLE_KEY||env.SUPABASE_ANON_KEY;const token=env.GHE_READ_TOKEN;if(!base||!key||!token)throw new Error("Configuration Supabase manquante");const r=await fetch(`${base}/rest/v1/rpc/ghe_read_v2`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json","x-ghe-token":token},body:JSON.stringify({p_mode:mode,p_agent:agent,p_type:type})});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}`);return t?JSON.parse(t):{}}
function mapList(x){return{ok:true,agents:(x?.agents||[]).map(a=>{const name=[a.nom,a.prenom].filter(Boolean).join(" ").trim();const av=avatar(a);return{...a,agent:a.source_key||a.agent_key,key:a.source_key||a.agent_key,agent_key:a.source_key||a.agent_key,nom:name,nomComplet:name,avatar_image_url:av,avatar_thumb_url:av,avatar_url:av,avatar_statut:av?"OK":"ABSENT"}})}}
function mapAgenda(x){const av=x?.avatar_url?x.avatar_url.replace(/\/file\/d\/([^/]+)\/.*/,"/thumbnail?id=$1&sz=w320"):"";return{...x,avatar_image_url:av,avatar_thumb_url:av,avatar_url:av,events:(x?.events||[]).map(e=>{const exact=e.source_value||e.shift_code||e.code||"";const h=hours(exact);return{...e,date:String(e.date||"").slice(0,10),horaire:h?`${h[0]}-${h[1]}`:"",titre:exact,description:e.observation||e.description||"",shift_code:exact,pastille:cleanShift(exact),alerte:""}})}}
const esc=v=>String(v||"").replace(/\\/g,"\\\\").replace(/\r?\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");
function plusDay(iso){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
const dt=(iso,time)=>iso.replace(/-/g,"")+"T"+time.replace(":","")+"00";
function toIcs(events,title){const l=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Planning GHE//Supabase//FR","CALSCALE:GREGORIAN","METHOD:PUBLISH",`X-WR-CALNAME:${esc(title||"Planning GHE")}`],stamp=new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");for(const e of events){if(!/^\d{4}-\d{2}-\d{2}$/.test(e.date||""))continue;l.push("BEGIN:VEVENT",`UID:${esc(e.uid||`${e.date}-${e.summary}`)}@planning.esapin.com`,`DTSTAMP:${stamp}`);if(e.start&&e.end){const endDate=e.end<=e.start?plusDay(e.date):e.date;l.push(`DTSTART;TZID=Europe/Paris:${dt(e.date,e.start)}`,`DTEND;TZID=Europe/Paris:${dt(endDate,e.end)}`)}else l.push(`DTSTART;VALUE=DATE:${e.date.replace(/-/g,"")}`,`DTEND;VALUE=DATE:${plusDay(e.date).replace(/-/g,"")}`);l.push(`SUMMARY:${esc(e.summary||"Planning")}`);if(e.description)l.push(`DESCRIPTION:${esc(e.description)}`);l.push("END:VEVENT")}l.push("END:VCALENDAR");return l.join("\r\n")+"\r\n"}
function text(body,type){return new Response(body,{headers:{"Content-Type":type,"Cache-Control":"no-store"}})}
export async function onRequest(context){const u=new URL(context.request.url),mode=String(u.searchParams.get("mode")||"health").toLowerCase(),cb=u.searchParams.get("callback")||"",agent=agentKey(u.searchParams.get("agent")||"");try{if(mode==="list"||mode==="avatars")return out(mapList(await rpc(context,"list")),200,cb);if(mode==="agenda")return out(mapAgenda(await rpc(context,"agenda",agent)),200,cb);if(mode==="ics"){const a=mapAgenda(await rpc(context,"agenda",agent));return text(toIcs(a.events.map(e=>{const h=hours(e.shift_code);return{date:e.date,start:h?.[0],end:h?.[1],summary:e.shift_code||"Planning",description:e.description||"",uid:`${agent}-${e.date}-${e.shift_code}`}}),a.nom?`Planning ${a.nom}`:"Planning GHE"),"text/calendar; charset=utf-8")}if(mode==="ics_collectif"){const type=String(u.searchParams.get("type")||"stagiaires").toLowerCase(),m=type.startsWith("form")?"formations":"stagiaires",x=await rpc(context,m);const ev=(x.items||[]).map(r=>({date:String(r.date_debut||"").slice(0,10),summary:m==="formations"?`🎓 ${r.intitule||"Formation"}`:`👶 ${[r.nom,r.prenom].filter(Boolean).join(" ")}`,description:m==="formations"?[r.horaire,r.lieu].filter(Boolean).join(" · "):[r.horaires,r.referent].filter(Boolean).join(" · ")}));return text(toIcs(ev,m==="formations"?"Formations GHE":"Stagiaires GHE"),"text/calendar; charset=utf-8")}if(mode==="formations"||mode==="stagiaires"||mode==="site_stagiaires_formations"){const m=mode==="site_stagiaires_formations"?(String(u.searchParams.get("type")||"stagiaires").startsWith("form")?"formations":"stagiaires"):mode;return out(await rpc(context,m),200,cb)}if(mode==="pdf_agent"){const month=String(u.searchParams.get("mois")||"");return out({ok:true,lien_pdf:`${u.origin}/apercu.html?type=agent&agent=${encodeURIComponent(agent)}${month?`&mois=${encodeURIComponent(month)}`:""}&print=1`,dynamique:true},200,cb)}if(mode==="health")return out(await rpc(context,"health"),200,cb);return out({ok:false,erreur:"Mode inconnu"},400,cb)}catch(e){console.error("ghe-data",e);return out({ok:false,erreur:"Données temporairement indisponibles"},500,cb)}}
